/*
 * Solution to Project Euler problem 2 using JavaScript.
 * Copyright (c) 2019 Jonathan Schneibel
 * MIT License: https://opensource.org/licenses/MIT
 * GitHub: https://github.com/jschneibel/project-euler-solutions
 */

/*
 * Problem 2:
 * Each new term in the Fibonacci sequence is generated by adding the previous
 * two terms. By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed
 * four million, find the sum of the even-valued terms.
 */

let sum = 0;
let f0 = 0;
let f1 = 1;
let f2 = 1;

while (f2 <= 4000000) {
  if (f2 % 2 == 0) sum += f2;
  f2 = f0 + f1;
  f0 = f1;
  f1 = f2;
}

let solution = sum;

console.log(solution);
